package com.situ.crm.mapper;

import java.util.List;

import com.situ.crm.entity.RolePermission;
import com.situ.crm.entity.RolePermissionKey;

public interface RolePermissionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_permission
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(RolePermissionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_permission
	 *
	 * @mbggenerated
	 */
	int insert(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_permission
	 *
	 * @mbggenerated
	 */
	int insertSelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_permission
	 *
	 * @mbggenerated
	 */
	RolePermission selectByPrimaryKey(RolePermissionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_permission
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_permission
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(RolePermission record);

	void deleteByRoleId(Integer id);

	List<Integer> selectPermissionIdsByRoleId(Integer roleId);
}